# sam deploy --stack-name fmarket-backend --s3-bucket lambda-package-$UID --capabilities CAPABILITY_IAM
# sam list endpoints --output json --stack-name fmarket-backend
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 10

Resources:
  FmarketBackendApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: 'prod'
  FmarketBackendFunction:
    Type: AWS::Serverless::Function
    Properties:
#      Role: arn:aws:iam::$ACCOUNT_ID:role/fmarket-lambda-role
      CodeUri: .
      Handler: com.fmarket.backend.LambdaHandler::handleRequest
      Runtime: java17
      AutoPublishAlias: production
#      SnapStart:
#        ApplyOn: PublishedVersions
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        FmarketBackendApi:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId:
              Ref: FmarketBackendApi
        FmarketBackendApiElse:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId:
              Ref: FmarketBackendApi
#      VpcConfig:
#        SecurityGroupIds:
#          - sg-07~~~
#        SubnetIds:
#          - subnet-09~~~
#          - subnet-09~~~
