# sam build
# sam deploy --stack-name barodream-backend --s3-bucket lambda-package-barodream --capabilities CAPABILITY_IAM
# sam list endpoints --output json --stack-name barodream-backend
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30

Resources:
  BarodreamBackendApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: 'prod'
  BarodreamBackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: arn:aws:iam::058264113304:role/barodream-lambda-role
      CodeUri: .
      Handler: com.barodream.backend.LambdaHandler::handleRequest
      Runtime: java17
      AutoPublishAlias: production
      #      SnapStart:
      #        ApplyOn: PublishedVersions
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        BarodreamBackendApi:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId:
              Ref: BarodreamBackendApi
        BarodreamBackendApiElse:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId:
              Ref: BarodreamBackendApi
      VpcConfig:
        SecurityGroupIds:
          - sg-02fae9390d8e34b2c
        SubnetIds:
          - subnet-0d6292e404a0ba5d5
          - subnet-0df194387a1a51264
